/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb']
    ABreadcrumbItem: typeof import('ant-design-vue/es')['BreadcrumbItem']
    AButton: typeof import('ant-design-vue/es')['Button']
    AccInfo: typeof import('./src/views/accQuery/accInfo/index.vue')['default']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    AUpload: typeof import('ant-design-vue/es')['Upload']
    AUploadDragger: typeof import('ant-design-vue/es')['UploadDragger']
    Error: typeof import('./src/views/error/index.vue')['default']
    FileOperate: typeof import('./src/views/settings/fileOperate/index.vue')['default']
    FpsRegister: typeof import('./src/views/transfer/fps/fpsRegister/index.vue')['default']
    FpsTransfer: typeof import('./src/views/transfer/fps/fpsTransfer/index.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Index: typeof import('./src/views/index/index.vue')['default']
    Layout: typeof import('./src/layout/index.vue')['default']
    LayoutContent: typeof import('./src/layout/components/LayoutContent.vue')['default']
    LayoutFooter: typeof import('./src/layout/components/LayoutFooter.vue')['default']
    LayoutHeader: typeof import('./src/layout/components/LayoutHeader.vue')['default']
    Login: typeof import('./src/views/login/index.vue')['default']
    OperateRecord: typeof import('./src/views/accQuery/operateRecord/index.vue')['default']
    PageView: typeof import('./src/layout/pageView.vue')['default']
    PhoneService: typeof import('./src/views/settings/phoneService/index.vue')['default']
    Register: typeof import('./src/views/register/index.vue')['default']
    RegisterIndex: typeof import('./src/views/register/registerIndex.vue')['default']
    RegisterResult: typeof import('./src/views/register/registerResult.vue')['default']
    ResetPassword: typeof import('./src/views/settings/resetPassword/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelfBankOnLocal: typeof import('./src/views/transfer/selfBankOnLocal/index.vue')['default']
    TransferRecord: typeof import('./src/views/accQuery/transferRecord/index.vue')['default']
    UpdatePwd: typeof import('./src/views/updatePwd/index.vue')['default']
    UpdatePwdConf: typeof import('./src/views/updatePwd/updatePwdConf.vue')['default']
    UpdatePwdInput: typeof import('./src/views/updatePwd/updatePwdInput.vue')['default']
    UpdatePwdResult: typeof import('./src/views/updatePwd/updatePwdResult.vue')['default']
  }
}
